#!/bin/bash

set -o errexit

ROOT=$(dirname $0)/..
cd ${ROOT}

docker-compose build >/dev/null 2>&1 || echo "docker-compose build failed!"

exec docker-compose run --no-deps --rm authstore go test github.com/cloudpipe/auth-store/... $@
